# Generated by Django 4.0.5 on 2022-06-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('key', models.CharField(editable=False, max_length=7, primary_key=True, serialize=False)),
                ('long_url', models.URLField(verbose_name='Long URL')),
                ('short_url', models.CharField(max_length=100)),
                ('visits', models.PositiveIntegerField(default=0, verbose_name='Visits')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'link',
                'verbose_name_plural': 'Most viewed links',
            },
        ),
    ]
