# Generated by Django 5.0.6 on 2024-06-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortUrl",
            fields=[
                (
                    "key",
                    models.CharField(
                        editable=False,
                        max_length=7,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("long_url", models.URLField(verbose_name="Long URL")),
                (
                    "visits",
                    models.PositiveIntegerField(default=0, verbose_name="Visits"),
                ),
            ],
        ),
    ]
