# Generated by Django 4.0.5 on 2022-06-22 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorturls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='created_at',
        ),
    ]
