version: '3.8'

volumes:
  postgres-data-dev:
  postgres-data-backups-dev:


services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    image: url-shortener-postgres-data
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
      - postgres-data-backups-dev:/backups
    env_file:
      - ./.env
    restart: unless-stopped

  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    image: url-shortener-backend
    volumes:
      - .:/usr/src/app
      - ./.env:/usr/src/app/.env
    command: /usr/src/app/docker/django/start_dev
    ports:
      - 8000:8000
    develop:
      # Create a `watch` configuration to update the app
      # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /usr/src/app
          # Exclude the project virtual environment
          ignore:
            - .venv/
        # Rebuild the image on changes to the `pyproject.toml`
        - action: rebuild
          path: ./pyproject.toml

    env_file:
      - ./.env
    depends_on:
      - postgres
    restart: unless-stopped
