#!/bin/sh


python manage.py makemigrations
python manage.py migrate
python manage.py collectstatic --no-input --clear
python manage.py createsuperuser --noinput
exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:8000 --chdir=/usr/src/app
