#!/bin/sh

uv run python /usr/src/app/manage.py flush --no-input
uv run python /usr/src/app/manage.py makemigrations
uv run python /usr/src/app/manage.py migrate
uv run python /usr/src/app/manage.py createsuperuser --noinput
uv run python /usr/src/app/manage.py runserver 0.0.0.0:8000
