#!/bin/sh


uv run /usr/src/app/manage.py makemigrations
uv run /usr/src/app/manage.py migrate
uv run /usr/src/app/manage.py collectstatic --no-input --clear
uv run /usr/src/app/manage.py createsuperuser --noinput
exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:8000 --chdir=/usr/src/app
